repos:
  - repo: https://github.com/awslabs/git-secrets
    rev: 5357e18bc27b42a827b6780564ea873a72ca1f01
    hooks:
      - id: git-secrets
        entry: /usr/bin/env
        args:
          # Using a bash script to ensure aws secrets rules is always installed.
          - bash
          - -c
          - |
            echo "Scanning with git-secrets..."
            git-secrets --register-aws
            if ! git-secrets --pre_commit_hook; then
              echo "Error: Potential secrets detected. Please review your changes."
              exit 1
            fi
            echo "No secrets detected."
