AWSTemplateFormatVersion: 2010-09-09
Description: Create Timestream Resources


Resources:
  MyDatabase:
    Type: AWS::Timestream::Database
    Properties:
      DatabaseName: "devops1"

  MyTable:
    DependsOn: MyDatabase
    Type: AWS::Timestream::Table
    Properties:
      DatabaseName: !Ref MyDatabase
      TableName : "sample_devops"
      RetentionProperties:
        MemoryStoreRetentionPeriodInHours: "24"
        MagneticStoreRetentionPeriodInDays: "7300"
      MagneticStoreWriteProperties:
        EnableMagneticStoreWrites: true
      Schema: 
        CompositePartitionKey: 
          - EnforcementInRecord: "REQUIRED"
            Name: "hostname"
            Type: "DIMENSION"