services:
  dashboard:
    # build: .
    image: fjpimproving/migration-dashboard:v1.0
    ports:
      - "8501:8501"
    volumes:
      - ./migration-logs:/app/migration-logs:ro
      - ./config.yaml:/app/config.yaml:ro
