version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "multiagent-observability-influxdb"
resolve_s3 = true
region = "us-west-2"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
disable_rollback = false
image_repositories = []
parameter_overrides = [
    "VpcId=vpc-xxxxxx",
    "SubnetIds=subnet-xxxxxx,subnet-xxxxxx",
    "AdminPassword=password",
    "WhitelistedIP=173.145.105.157/32",
    "InstanceType=db.influx.medium"
]
