[package]
name = "sample-timestream-app"
version = "0.1.0"
edition = "2021"

[dependencies]
aws-config = { version = "1.1.7", features = ["behavior-version-latest"] }
aws-sdk-timestreamwrite = "1.25.0"
chrono = "0.4.38"
tokio = { version = "1.38", features = ["full"] }
csv = "1.3.0"
